# Render Blueprint for ChurrasApp
services:
  # Frontend - Static Site
  - type: web
    name: churrasapp-frontend
    env: static
    staticPublishPath: ./apps/web/build
    buildCommand: npm ci && npm run build:web
    headers:
      - path: "/*"
        name: Cache-Control
        value: "public, max-age=3600"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

  # Backend - Web Service
  - type: web
    name: churrasapp-backend
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm run start:api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: churrasapp-backend
          property: port
    healthCheckPath: /health

# Optional: Database (if needed later)
# databases:
#   - name: churrasapp-db
#     databaseName: churrasapp
#     user: churrasapp_user
